#! /usr/bin/env bash

INV_IP=$(which inv_ip)

if [[ -z "${INV_IP}" ]]
then
	echo "The script 'inv_ip' is not in your path. Please check the installation and your executable path." 1>&2
	exit -1
fi

USER=""

# Get optional user argument
while getopts ":u:" opt
do
	case ${opt} in
		u ) USER="${OPTARG}@"
		    ;;
		\?) echo "Invalid option \"${OPTARG}\"."
		    exit -1
		    ;;
	esac
done
shift $((OPTIND - 1))

# Get required environment and target args
ENV=${1}
shift
TARGET=${1}
shift

IP_TARGET=$(${INV_IP} ${ENV} ${TARGET})

if [[ "1" != $(wc -l <<<"${IP_TARGET}") ]]
then
	echo "Found multiple targets for the ${ENV} inventory targeting \"${TARGET}\"." 1>&2
	echo "Results:" 1>&2
	echo "${IP_TARGET}" 1>&2
	exit -2
fi

ssh ${USER}${IP_TARGET} $@

exit $?
